export const PRODUTOS = [
  {
    id: 1,
    slug: 'luna',
    nome: 'Desodorante Colônia Luna 75ml',
    marca: 'Natura',
    categoria: 'perfumaria',
    preco: 189.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/luna.jpg',
    resumo: 'Colônia feminina marcada pela flor de luna, delicada e sofisticada.',
    descricao:
      'A Desodorante Colônia Luna de Natura é uma fragrância feminina equilibrada, com um coração floral marcante e um fundo amadeirado. Ideal para o dia a dia, tem fixação moderada e projeta um rastro delicado e elegante.',
    especificacoes: {
      'Família olfativa': 'Floral Amadeirado',
      'Conteúdo': '75ml',
      'Como aplicar': 'Borrifar nos pontos de pulso, pescoço e atrás das orelhas.',
      'Indicado para': 'Uso diário',
    },
    composicao: 'Álcool, água, fragrância e componentes da marca Natura.',
    modoUso:
      'Borrifar diretamente sobre a pele nas áreas de pulsação, mantendo a embalagem a cerca de 15 cm de distância.',
    destaque: true,
  },
  {
    id: 2,
    slug: 'empire-woman',
    nome: 'Empire Woman Deo Colônia 100ml',
    marca: 'Hinode',
    categoria: 'perfumaria',
    preco: 179.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/empire-woman.png',
    resumo: 'Fragrância feminina sofisticada, com assinatura chipre moderna.',
    descricao:
      'Empire Woman Deo Colônia é a fragrância da Hinode que representa mulheres protagonistas. Uma assinatura olfativa chipre, moderna e elegante, com projeção marcante, ideal para momentos que pedem presença e sofisticação.',
    especificacoes: {
      'Família olfativa': 'Chipre Moderno',
      'Conteúdo': '100ml',
      'Notas de topo': 'Frutais e aldeídos',
      'Notas de fundo': 'Patchouli, âmbar e musk',
    },
    composicao: 'Álcool, água, fragrância e componentes da marca Hinode.',
    modoUso: 'Aplicar nos pontos de pulsação — pulsos, pescoço e atrás das orelhas.',
    destaque: false,
  },
  {
    id: 3,
    slug: 'malbec',
    nome: 'Malbec Eau de Parfum 90ml',
    marca: 'O Boticário',
    categoria: 'perfumaria',
    preco: 189.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/malbec.jpg',
    resumo: 'Perfume masculino marcante e elegante, com presença inconfundível.',
    descricao:
      'Malbec Eau de Parfum de O Boticário é uma fragrância masculina intensa, que une madeiras nobres e especiarias a um fundo de âmbar e vetiver. Combina estilo, masculinidade e longa duração, deixando um rastro marcante por onde passa.',
    especificacoes: {
      'Família olfativa': 'Amadeirado Especiado',
      'Conteúdo': '90ml',
      'Fixação': 'Longa duração',
      'Notas de fundo': 'Vetiver, âmbar e madeiras',
    },
    composicao: 'Álcool, água, fragrância e componentes da marca O Boticário.',
    modoUso: 'Aplicar nos pontos de pulso e pescoço. Ideal para ocasiões especiais.',
    destaque: true,
  },
  {
    id: 4,
    slug: 'tododia',
    nome: 'Creme Desodorante Nutritivo para o Corpo Tododia Algodão 400ml',
    marca: 'Natura',
    categoria: 'corpo-e-banho',
    preco: 89.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/tododia.jpg',
    resumo: 'Hidratação nutritiva e perfumação suave de algodão para o corpo.',
    descricao:
      'O Creme Desodorante Nutritivo Tododia Algodão hidrata profundamente a pele com uma textura cremosa de rápida absorção, deixando a pele perfumada com a delicada fragrância de algodão, uma das mais amadas da linha Tododia.',
    especificacoes: {
      'Benefício': 'Hidratação nutritiva de longa duração',
      'Conteúdo': '400ml',
      'Textura': 'Creme de rápida absorção',
      'Fragrância': 'Algodão',
    },
    composicao: 'Água, emolientes, glicerina, fragrância e ativos Natura.',
    modoUso: 'Aplicar sobre a pele limpa e seca com movimentos circulares, principalmente após o banho.',
    destaque: true,
  },
  {
    id: 5,
    slug: 'lily-creme',
    nome: 'Creme Acetinado Hidratante Desodorante Corporal Lily 250g',
    marca: 'O Boticário',
    categoria: 'corpo-e-banho',
    preco: 99.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/lily-creme.jpg',
    resumo: 'Textura acetinada que hidrata e deixa a pele perfumada de Lily.',
    descricao:
      'O Creme Acetinado Hidratante Corporal Lily hidrata e perfuma a pele com a fragrância floral de lírio. Sua textura acetinada desliza facilmente e proporciona sensação de pele macia, suave e delicadamente perfumada por mais tempo.',
    especificacoes: {
      'Benefício': 'Hidratação e perfumação prolongada',
      'Conteúdo': '250g',
      'Textura': 'Acetinada, de rápida absorção',
      'Fragrância': 'Floral de Lírio (Lily)',
    },
    composicao: 'Água, emolientes, glicerina, fragrância e componentes O Boticário.',
    modoUso: 'Aplicar abundantemente sobre a pele após o banho, espalhando em movimentos circulares.',
    destaque: false,
  },
  {
    id: 6,
    slug: 'malbec-lo',
    nome: 'Loção Hidratante Desodorante Corporal Malbec 200ml',
    marca: 'O Boticário',
    categoria: 'corpo-e-banho',
    preco: 89.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/malbec-lo.jpg',
    resumo: 'Hidratação com o rastro masculino marcante de Malbec.',
    descricao:
      'A Loção Hidratante Desodorante Corporal Malbec hidrata a pele ao mesmo tempo em que deixa o rastro inconfundível da fragrância Malbec. Textura leve, de rápida absorção, ideal para prolongar a perfumação da linha.',
    especificacoes: {
      'Benefício': 'Hidratação e perfumação prolongada',
      'Conteúdo': '200ml',
      'Textura': 'Leve, de rápida absorção',
      'Fragrância': 'Malbec (masculina)',
    },
    composicao: 'Água, emolientes, glicerina, fragrância e componentes O Boticário.',
    modoUso: 'Aplicar sobre a pele limpa e seca após o banho, espalhando até completa absorção.',
    destaque: false,
  },
  {
    id: 7,
    slug: 'shampoo-pataua',
    nome: 'Shampoo Ekos Patauá 100ml',
    marca: 'Natura',
    categoria: 'cabelos',
    preco: 59.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/shampoo-pataua.jpg',
    resumo: 'Limpeza suave e nutrição para os fios com o poder do patauá da Amazônia.',
    descricao:
      'O Shampoo Ekos Patauá de Natura proporciona limpeza suave enquanto nutre os fios com a riqueza do patauá, do ativo brasileiro da Amazônia. Deixa o cabelo macio, com brilho e com o cuidado feito para o seu cabelo.',
    especificacoes: {
      'Benefício': 'Limpeza suave e nutrição',
      'Conteúdo': '100ml',
      'Ativo': 'Patauá (ativo amazônico)',
      'Indicado para': 'Todos os tipos de cabelo',
    },
    composicao: 'Água, tensoativos suaves, patauá e ativos Natura.',
    modoUso: 'Aplicar sobre os cabelos molhados, massagear o couro cabeludo e enxaguar. Repetir se necessário.',
    destaque: false,
  },
  {
    id: 8,
    slug: 'sophie',
    nome: 'Shampoo Definição de Cachos Sophie 200ml',
    marca: 'O Boticário',
    categoria: 'cabelos',
    preco: 39.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/sophie.jpg',
    resumo: 'Limpeza que define e valoriza os cachos com leveza.',
    descricao:
      'O Shampoo Definição de Cachos Sophie é desenvolvido para cabelos crespos e cacheados. Limpa suavemente com os cuidados da linha Sophie, ajudando a valorizar a definição dos cachos, reduzir o frizz e manter o formato natural dos fios.',
    especificacoes: {
      'Benefício': 'Definição de cachos e controle do frizz',
      'Conteúdo': '200ml',
      'Indicado para': 'Cabelos crespos e cacheados',
      'Linha': 'Sophie',
    },
    composicao: 'Água, tensoativos suaves, ativos de definição e componentes O Boticário.',
    modoUso: 'Aplicar nos cabelos molhados, massagear suavemente e enxaguar em seguida.',
    destaque: true,
  },
  {
    id: 9,
    slug: 'lily-shampoo',
    nome: 'Shampoo Acetinado Lily 250ml',
    marca: 'O Boticário',
    categoria: 'cabelos',
    preco: 45.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/lily-shampoo.jpg',
    resumo: 'Toque aveludado e hidratação para todos os tipos de cabelo.',
    descricao:
      'O Shampoo Acetinado Lily traz a fragrância tão amada da linha, agora com o toque aveludado para os fios. Indicado para todos os tipos de cabelo, proporciona hidratação intensa e aveludada, promovendo fios fortes e com brilho.',
    especificacoes: {
      'Benefício': 'Hidratação intensa e toque aveludado',
      'Conteúdo': '250ml',
      'Indicado para': 'Todos os tipos de cabelo',
      'Fragrância': 'Lily',
    },
    composicao: 'Água, tensoativos suaves, ativos hidratantes e componentes O Boticário.',
    modoUso: 'Aplicar nos cabelos molhados, massagear o couro cabeludo e enxaguar bem.',
    destaque: false,
  },
  {
    id: 10,
    slug: 'lash-love',
    nome: 'Máscara para Cílios Lash Love 8g — Mary Kay',
    marca: 'Mary Kay',
    categoria: 'maquiagem',
    preco: 79.9,
    parcelas: 1,
    disponibilidade: 'ultimas-unidades',
    imagem: '/assets/images/prod/lash-love.jpg',
    resumo: 'Define, protege e dá volume aos cílios com fórmula condicionante.',
    descricao:
      'A Máscara para Cílios Lash Love Mary Kay oferece definição, proteção e proporciona mais volume com aparência naturalmente impecável. Seu aplicador flexível separa os fios e a fórmula com Panthenol-Pro Complex® e Vitamina E ajuda a hidratar e condicionar.',
    especificacoes: {
      'Efeito': 'Alonga, define e dá volume',
      'Conteúdo': '8g',
      'Cor': 'Preto',
      'Diferencial': 'Fórmula com Vitamina E',
    },
    composicao: 'Fórmula com Panthenol-Pro Complex® e Vitamina E (marykay)',
    modoUso: 'Aplicar da raiz às pontas dos cílios em movimento de zigue-zague. Retirar com demaquilante suave.',
    destaque: false,
  },
  {
    id: 11,
    slug: 'batom-matte',
    nome: 'Batom Matte Mary Kay 3,3g',
    marca: 'Mary Kay',
    categoria: 'maquiagem',
    preco: 69.9,
    parcelas: 1,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/batom-matte.png',
    resumo: 'Acabamento matte confortável, com cores intensas e sofisticadas.',
    descricao:
      'O Batom Matte Mary Kay une a sofisticação do acabamento matte ao conforto na aplicação. Sua textura desliza facilmente sobre os lábios, garantindo cobertura intensa e uniforme desde a primeira camada, disponível em diversas cores.',
    especificacoes: {
      'Acabamento': 'Matte confortável',
      'Conteúdo': '3,3g',
      'Cobertura': 'Intensa e uniforme',
      'Disponível em': 'Várias cores',
    },
    composicao: 'Ceras e emolientes de longa duração (marykay)',
    modoUso: 'Aplicar diretamente sobre os lábios, do centro para as bordas.',
    destaque: true,
  },
  {
    id: 12,
    slug: 'base-timewise',
    nome: 'Base TimeWise 3D 30ml — Mary Kay',
    marca: 'Mary Kay',
    categoria: 'maquiagem',
    preco: 149.9,
    parcelas: 3,
    disponibilidade: 'disponivel',
    imagem: '/assets/images/prod/base-timewise.png',
    resumo: 'Base matte de longa duração com benefícios de tratamento para a pele.',
    descricao:
      'A Base TimeWise 3D de Mary Kay une maquiagem e tratamento. Com acabamento matte confortável e controle da oleosidade por até 12 horas, tem cobertura média que pode ser construída, e o Complexo Age Minimize 3D® cuida da pele enquanto você se maquia.',
    especificacoes: {
      'Acabamento': 'Matte confortável',
      'Conteúdo': '30ml',
      'Duração': 'Até 12 horas',
      'Disponível em': 'Diversos tons',
    },
    composicao: 'Fórmula com Complexo Age Minimize 3D® (marykay)',
    modoUso: 'Aplicar uma pequena quantidade no rosto e espalhar com pincel, esponja ou ponta dos dedos.',
    destaque: true,
  },
];

export function buscarProduto(slug) {
  return PRODUTOS.find((produto) => produto.slug === slug || String(produto.id) === String(slug));
}

export function produtosDaCategoria(id) {
  return PRODUTOS.filter((produto) => produto.categoria === id);
}

export function formatarBRL(valor) {
  return (Number(valor) || 0).toLocaleString('pt-BR', {
    style: 'currency',
    currency: 'BRL',
  });
}

export function estoqueLabel(produto) {
  const disponibilidade = produto?.disponibilidade || 'disponivel';
  if (disponibilidade === 'indisponivel') return { txt: 'Indisponível', cls: 'est-indisponivel' };
  if (disponibilidade === 'ultimas-unidades') return { txt: 'Últimas unidades', cls: 'est-ultimas' };
  return { txt: 'Disponível', cls: 'est-disponivel' };
}
